# Generated by Django 4.2.2 on 2023-06-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="postq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answers", models.TextField()),
                (
                    "likes",
                    models.ManyToManyField(related_name="likess", to="qapp.postq"),
                ),
            ],
        ),
    ]
