# Generated by Django 4.2.2 on 2023-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="postqu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answers", models.TextField()),
                ("like", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50)),
                ("passwd", models.CharField(max_length=50)),
            ],
        ),
    ]
