# Generated by Django 4.2.2 on 2023-06-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qapp", "0002_postqu_signup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postqu",
            name="like",
            field=models.CharField(max_length=10),
        ),
    ]
